In [42]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import csv 
import edgar
import os
import pickle
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

In [52]:
df=pickle.load(open(r'C:\Users\ANN SERENA\Desktop\df_All_with2019',"rb"))
df

{'quarter_0': 2                  filing index date_reported                NAME OF ISSUER  \
 4    0001567619-19-002790          2019-02-08                         AECOM
 5    0001567619-19-002790          2019-02-08                 ALLSTATE CORP
 6    0001567619-19-002790          2019-02-08                    AMDOCS LTD
 7    0001567619-19-002790          2019-02-08     AMERICAN EQUITY INVT LIFE
 8    0001567619-19-002790          2019-02-08  AMERICAN INTERNATIONAL GROUP
 ..                          ...           ...                           ...
 189  0000949509-19-000003          2019-02-15        WHITING PETROLEUM CORP
 190  0000949509-19-000003          2019-02-15                   WORKDAY INC
 191  0000949509-19-000003          2019-02-15                   YANDEX NV-A
 192  0000949509-19-000003          2019-02-15             YETI HOLDINGS INC
 193  0000949509-19-000003          2019-02-15        YUM CHINA HOLDINGS INC

 2    TITLE OF CLASS      CUSIP (x$1000)   PRN AMT  PRN      CIK  \
 4               COM  00766T100    85862   3240077   SH  1027796
 5               COM  020002101    47191    571110   SH  1027796
 6               COM  G02602103      615     10496   SH  1027796
 7               COM  025676206    34131   1221599   SH  1027796
 8               COM  026874784   475674  12069892   SH  1027796
 ..              ...        ...      ...       ...  ...      ...
 189  CV SR UNSEC NT  966387AL6    21537  22720000  PRN   949509
 190  CV SR UNSEC NT  98138HAF8    15528  12658000  PRN   949509
 191    Common Stock  N97284108    16435    600903   SH   949509
 192    COMMON STOCK  98585X104     9408    633938   SH   949509
 193    Common Stock  98850P109    30183    900168   SH   949509

 2                         Entity name
 4    PZENA INVESTMENT MANAGEMENT LLC
 5    PZENA INVESTMENT MANAGEMENT LLC
 6    PZENA INVESTMENT MANAGEMENT LLC
 7    PZENA INVESTMENT MANAGEMENT LLC
 8    PZENA INVESTMENT MANAGEMENT LLC
 ..                                ...
 189    OAKTREE CAPITAL MANAGEMENT LP
 190    OAKTREE CAPITAL MANAGEMENT LP
 191    OAKTREE CAPITAL MANAGEMENT LP
 192    OAKTREE CAPITAL MANAGEMENT LP
 193    OAKTREE CAPITAL MANAGEMENT LP

 [61425 rows x 10 columns],
 'quarter_1': 2                  filing index date_reported                NAME OF ISSUER  \
 4    0001567619-19-009752          2019-05-03                         AECOM
 5    0001567619-19-009752          2019-05-03                 ALLSTATE CORP
 6    0001567619-19-009752          2019-05-03                    AMDOCS LTD
 7    0001567619-19-009752          2019-05-03     AMERICAN EQUITY INVT LIFE
 8    0001567619-19-009752          2019-05-03  AMERICAN INTERNATIONAL GROUP
 ..                          ...           ...                           ...
 208  0000949509-19-000006          2019-05-14             YETI HOLDINGS INC
 209  0000949509-19-000006          2019-05-14        YUM CHINA HOLDINGS INC
 210  0000949509-19-000006          2019-05-14                   ZENDESK INC
 211  0000949509-19-000006          2019-05-14              ZILLOW GROUP INC
 212  0000949509-19-000006          2019-05-14              ZILLOW GROUP INC

 2        TITLE OF CLASS      CUSIP (x$1000)   PRN AMT  PRN      CIK  \
 4                   COM  00766T100    79461   2678166   SH  1027796
 5                   COM  020002101    23761    252290   SH  1027796
 6                   COM  G02602103      741     13695   SH  1027796
 7                   COM  025676206    31890   1180245   SH  1027796
 8                   COM  026874784   529806  12303898   SH  1027796
 ..                  ...        ...      ...       ...  ...      ...
 208        COMMON STOCK  98585X104    19177    633938   SH   949509
 209        Common Stock  98850P109    33437    744536   SH   949509
 210      CV SR UNSEC NT  98936JAB7     5604   3835000  PRN   949509
 211  CV SR UNSEC NT PNC  98954MAB7    22097  21554000  PRN   949509
 212  CV SR UNSEC NT PNC  98954MAC5    20357  22227000  PRN   949509

 2                         Entity name
 4    PZENA INVESTMENT MANAGEMENT LLC
 5    PZENA INVESTMENT MANAGEMENT LLC
 6    PZENA INVESTMENT MANAGEMENT LLC
 7    PZENA INVESTMENT MANAGEMENT LLC
 8    PZENA INVESTMENT MANAGEMENT LLC
 ..                                ...
 208    OAKTREE CAPITAL MANAGEMENT LP
 209    OAKTREE CAPITAL MANAGEMENT LP
 210    OAKTREE CAPITAL MANAGEMENT LP
 211    OAKTREE CAPITAL MANAGEMENT LP
 212    OAKTREE CAPITAL MANAGEMENT LP

 [60165 rows x 10 columns],
 'quarter_2': 2                  filing index date_reported                NAME OF ISSUER  \
 4    0001567619-19-015705          2019-08-02                         AECOM
 5    0001567619-19-015705          2019-08-02                 ALLSTATE CORP
 6    0001567619-19-015705          2019-08-02                    AMDOCS LTD
 7    0001567619-19-015705          2019-08-02     AMERICAN EQUITY INVT LIFE
 8    0001567619-19-015705          2019-08-02  AMERICAN INTERNATIONAL GROUP
 ..                          ...           ...                           ...
 204  0000949509-19-000008          2019-08-14                   WORKDAY INC
 205  0000949509-19-000008          2019-08-14                   YANDEX NV-A
 206  0000949509-19-000008          2019-08-14             YETI HOLDINGS INC
 207  0000949509-19-000008          2019-08-14              ZILLOW GROUP INC
 208  0000949509-19-000008          2019-08-14              ZILLOW GROUP INC

 2        TITLE OF CLASS      CUSIP (x$1000)   PRN AMT  PRN      CIK  \
 4                   COM  00766T100   104193   2752783   SH  1027796
 5                   COM  020002101    25655    252290   SH  1027796
 6                   COM  G02602103      831     13380   SH  1027796
 7                   COM  025676206    31628   1164523   SH  1027796
 8                   COM  026874784   580468  10894670   SH  1027796
 ..                  ...        ...      ...       ...  ...      ...
 204      CV SR UNSEC NT  98138HAF8     2516   1675000  PRN   949509
 205        Common Stock  N97284108    22155    583020   SH   949509
 206        COMMON STOCK  98585X104    15564    537629   SH   949509
 207  CV SR UNSEC NT PNC  98954MAB7     9703   8554000  PRN   949509
 208  CV SR UNSEC NT PNC  98954MAC5    18048  18289000  PRN   949509

 2                         Entity name
 4    PZENA INVESTMENT MANAGEMENT LLC
 5    PZENA INVESTMENT MANAGEMENT LLC
 6    PZENA INVESTMENT MANAGEMENT LLC
 7    PZENA INVESTMENT MANAGEMENT LLC
 8    PZENA INVESTMENT MANAGEMENT LLC
 ..                                ...
 204    OAKTREE CAPITAL MANAGEMENT LP
 205    OAKTREE CAPITAL MANAGEMENT LP
 206    OAKTREE CAPITAL MANAGEMENT LP
 207    OAKTREE CAPITAL MANAGEMENT LP
 208    OAKTREE CAPITAL MANAGEMENT LP

 [62613 rows x 10 columns],
 'quarter_3': 2                  filing index date_reported          NAME OF ISSUER  \
 4    0001567619-19-020281          2019-11-01         ACTUANT CORP- A
 5    0001567619-19-020281          2019-11-01                   AECOM
 6    0001567619-19-020281          2019-11-01                AES CORP
 7    0001567619-19-020281          2019-11-01           ALLSTATE CORP
 8    0001567619-19-020281          2019-11-01              AMDOCS LTD
 ..                          ...           ...                     ...
 200  0000949509-19-000010          2019-11-13             WIX.COM LTD
 201  0000949509-19-000010          2019-11-13             YANDEX NV-A
 202  0000949509-19-000010          2019-11-13       YETI HOLDINGS INC
 203  0000949509-19-000010          2019-11-13  YPF S.A.-SPONSORED ADR
 204  0000949509-19-000010          2019-11-13        ZILLOW GROUP INC

 2        TITLE OF CLASS      CUSIP (x$1000)  PRN AMT  PRN      CIK  \
 4                   COM  00508X203    95331  4345098   SH  1027796
 5                   COM  00766T100    94061  2504285   SH  1027796
 6                   COM  00130H105      854    52251   SH  1027796
 7                   COM  020002101    22999   211623   SH  1027796
 8                   COM  G02602103      869    13152   SH  1027796
 ..                  ...        ...      ...      ...  ...      ...
 200      CV SR UNSEC NT  92940WAB5     1102   990000  PRN   949509
 201        Common Stock  N97284108    17115   488857   SH   949509
 202        COMMON STOCK  98585X104    15054   537629   SH   949509
 203                 ADR  984245100    13340  1442103   SH   949509
 204  CV SR UNSEC NT PNC  98954MAC5     5576  6314000  PRN   949509

 2                         Entity name
 4    PZENA INVESTMENT MANAGEMENT LLC
 5    PZENA INVESTMENT MANAGEMENT LLC
 6    PZENA INVESTMENT MANAGEMENT LLC
 7    PZENA INVESTMENT MANAGEMENT LLC
 8    PZENA INVESTMENT MANAGEMENT LLC
 ..                                ...
 200    OAKTREE CAPITAL MANAGEMENT LP
 201    OAKTREE CAPITAL MANAGEMENT LP
 202    OAKTREE CAPITAL MANAGEMENT LP
 203    OAKTREE CAPITAL MANAGEMENT LP
 204    OAKTREE CAPITAL MANAGEMENT LP

 [62877 rows x 10 columns]}

In [59]:
adj1= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_19q1", "rb"))
adj2= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_19q2", "rb"))
adj3= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_19q3", "rb"))
adj4= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_19q4", "rb"))
adj5= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_20q1", "rb"))
adj6= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_20q2", "rb"))
adj7= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_20q3", "rb"))
adj8= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_20q4", "rb"))
adj9= pickle.load(open(r"C:\Users\ANN SERENA\Desktop\Adjacency matrices\adj_21q1", "rb"))

In [60]:
np.random.seed(3)
G1 = nx.from_numpy_matrix(adj1)
G2 = nx.from_numpy_matrix(adj2)
G3 = nx.from_numpy_matrix(adj3)
G4 = nx.from_numpy_matrix(adj4)
G5 = nx.from_numpy_matrix(adj5)
G6 = nx.from_numpy_matrix(adj6)
G7 = nx.from_numpy_matrix(adj7)
G8 = nx.from_numpy_matrix(adj8)
G9 = nx.from_numpy_matrix(adj9)

Centrality measures for 2019

In [62]:
bb1 = nx.betweenness_centrality(G1)
cc1 = nx.closeness_centrality(G1)
dc1 = nx.degree_centrality(G1)
centrality = {j:{'betweenness':bb1[j],'closeness': cc1[j],'degree': dc1[j]} for i,j in enumerate(G1.nodes)}
nx.set_node_attributes(G1, centrality)

bb2 = nx.betweenness_centrality(G2)
cc2 = nx.closeness_centrality(G2)
dc2 = nx.degree_centrality(G2)
centrality = {j:{'betweenness':bb2[j],'closeness': cc2[j],'degree': dc2[j]} for i,j in enumerate(G2.nodes)}
nx.set_node_attributes(G2, centrality)

bb3 = nx.betweenness_centrality(G3)
cc3 = nx.closeness_centrality(G3)
dc3 = nx.degree_centrality(G3)
centrality = {j:{'betweenness':bb3[j],'closeness': cc3[j],'degree': dc3[j]} for i,j in enumerate(G3.nodes)}
nx.set_node_attributes(G3, centrality)

bb4 = nx.betweenness_centrality(G4)
cc4 = nx.closeness_centrality(G4)
dc4 = nx.degree_centrality(G4)
centrality = {j:{'betweenness':bb4[j],'closeness': cc4[j],'degree': dc4[j]} for i,j in enumerate(G4.nodes)}
nx.set_node_attributes(G4, centrality)

In [70]:
summary1= pd.DataFrame({'betweenness':bb1, 'closeness':cc1, 'degree':dc1}).reset_index()
summary2= pd.DataFrame({'betweenness':bb2, 'closeness':cc2, 'degree':dc2}).reset_index()
summary3= pd.DataFrame({'betweenness':bb3, 'closeness':cc3, 'degree':dc3}).reset_index()
summary4= pd.DataFrame({'betweenness':bb4, 'closeness':cc4, 'degree':dc4}).reset_index()

In [64]:
summary1

    index  betweenness  closeness    degree
0       0     0.001170   0.950000  1.052632
1       1     0.005476   1.000000  1.105263
2       2     0.005476   1.000000  1.105263
3       3     0.001170   0.950000  1.052632
4       4     0.001170   0.950000  1.052632
5       5     0.005476   1.000000  1.105263
6       6     0.000000   0.703704  0.684211
7       7     0.005476   1.000000  1.105263
8       8     0.001170   0.950000  1.052632
9       9     0.000000   0.904762  1.000000
10     10     0.000000   0.904762  1.000000
11     11     0.001170   0.950000  1.052632
12     12     0.005476   1.000000  1.105263
13     13     0.003721   0.950000  1.052632
14     14     0.005476   1.000000  1.105263
15     15     0.005476   1.000000  1.105263
16     16     0.000000   0.826087  0.894737
17     17     0.005476   1.000000  1.105263
18     18     0.005476   1.000000  1.105263
19     19     0.005476   1.000000  1.105263

In [77]:
frames1= [summary1, summary2, summary3, summary4]
result1=pd.concat(frames1)
result1

    index  betweenness  closeness    degree
0       0     0.001170   0.950000  1.052632
1       1     0.005476   1.000000  1.105263
2       2     0.005476   1.000000  1.105263
3       3     0.001170   0.950000  1.052632
4       4     0.001170   0.950000  1.052632
..    ...          ...        ...       ...
15     15     0.007654   1.000000  1.105263
16     16     0.000975   0.730769  0.736842
17     17     0.007654   1.000000  1.105263
18     18     0.007654   1.000000  1.105263
19     19     0.006778   0.950000  1.052632

[80 rows x 4 columns]

Centrality measures for 2020

In [74]:
bb5 = nx.betweenness_centrality(G5)
cc5 = nx.closeness_centrality(G5)
dc5 = nx.degree_centrality(G5)
centrality = {j:{'betweenness':bb5[j],'closeness': cc5[j],'degree': dc5[j]} for i,j in enumerate(G5.nodes)}
nx.set_node_attributes(G5, centrality)

bb6 = nx.betweenness_centrality(G6)
cc6 = nx.closeness_centrality(G6)
dc6 = nx.degree_centrality(G6)
centrality = {j:{'betweenness':bb6[j],'closeness': cc6[j],'degree': dc6[j]} for i,j in enumerate(G6.nodes)}
nx.set_node_attributes(G6, centrality)

bb7 = nx.betweenness_centrality(G7)
cc7 = nx.closeness_centrality(G7)
dc7 = nx.degree_centrality(G7)
centrality = {j:{'betweenness':bb7[j],'closeness': cc7[j],'degree': dc7[j]} for i,j in enumerate(G7.nodes)}
nx.set_node_attributes(G7, centrality)

bb8 = nx.betweenness_centrality(G8)
cc8 = nx.closeness_centrality(G8)
dc8 = nx.degree_centrality(G8)
centrality = {j:{'betweenness':bb8[j],'closeness': cc8[j],'degree': dc8[j]} for i,j in enumerate(G8.nodes)}
nx.set_node_attributes(G8, centrality)

In [75]:
summary5= pd.DataFrame({'betweenness':bb5, 'closeness':cc5, 'degree':dc5}).reset_index()
summary6= pd.DataFrame({'betweenness':bb6, 'closeness':cc6, 'degree':dc6}).reset_index()
summary7= pd.DataFrame({'betweenness':bb7, 'closeness':cc7, 'degree':dc7}).reset_index()
summary8= pd.DataFrame({'betweenness':bb8, 'closeness':cc8, 'degree':dc8}).reset_index()

In [86]:
frames2= [summary5, summary6, summary7, summary8]
result2=pd.concat(frames2)
result2

    index  betweenness  closeness    degree
0       0     0.004021   0.950000  1.052632
1       1     0.006908   1.000000  1.105263
2       2     0.006908   1.000000  1.105263
3       3     0.000344   0.904762  1.000000
4       4     0.006908   1.000000  1.105263
5       5     0.006908   1.000000  1.105263
6       6     0.001363   0.760000  0.789474
7       7     0.002886   0.904762  1.000000
8       8     0.000344   0.904762  1.000000
9       9     0.000344   0.904762  1.000000
10     10     0.000344   0.904762  1.000000
11     11     0.000344   0.904762  1.000000
12     12     0.006908   1.000000  1.105263
13     13     0.003230   0.950000  1.052632
14     14     0.006908   1.000000  1.105263
15     15     0.006908   1.000000  1.105263
16     16     0.000450   0.730769  0.736842
17     17     0.006908   1.000000  1.105263
18     18     0.006908   1.000000  1.105263
19     19     0.006032   0.950000  1.052632
0       0     0.004924   0.947368  1.055556
1       1     0.008440   1.000000  1.111111
2       2     0.008440   1.000000  1.111111
3       3     0.000408   0.900000  1.000000
4       4     0.008440   1.000000  1.111111
5       5     0.008440   1.000000  1.111111
6       6     0.001656   0.750000  0.777778
7       7     0.003516   0.900000  1.000000
8       8     0.000408   0.900000  1.000000
9       9     0.000408   0.900000  1.000000
10     10     0.000408   0.900000  1.000000
11     11     0.000408   0.900000  1.000000
12     12     0.008440   1.000000  1.111111
13     13     0.008440   1.000000  1.111111
14     14     0.008440   1.000000  1.111111
15     15     0.000545   0.720000  0.722222
16     16     0.003924   0.947368  1.055556
17     17     0.008440   1.000000  1.111111
18     18     0.007378   0.947368  1.055556
0       0     0.004519   0.950000  1.052632
1       1     0.007405   1.000000  1.105263
2       2     0.007405   1.000000  1.105263
3       3     0.000000   0.904762  1.000000
4       4     0.007405   1.000000  1.105263
5       5     0.007405   1.000000  1.105263
6       6     0.001595   0.760000  0.789474
7       7     0.002886   0.950000  1.052632
8       8     0.000000   0.904762  1.000000
9       9     0.000000   0.904762  1.000000
10     10     0.000000   0.904762  1.000000
11     11     0.000000   0.904762  1.000000
12     12     0.007405   1.000000  1.105263
13     13     0.002886   0.950000  1.052632
14     14     0.007405   1.000000  1.105263
15     15     0.007405   1.000000  1.105263
16     16     0.000450   0.703704  0.684211
17     17     0.002886   0.950000  1.052632
18     18     0.007405   1.000000  1.105263
19     19     0.007405   1.000000  1.105263
0       0     0.004527   0.947368  1.055556
1       1     0.008102   1.000000  1.111111
2       2     0.008102   1.000000  1.111111
3       3     0.000903   0.900000  1.000000
4       4     0.008102   1.000000  1.111111
5       5     0.008102   1.000000  1.111111
6       6     0.001030   0.750000  0.777778
7       7     0.003575   0.900000  1.000000
8       8     0.000903   0.900000  1.000000
9       9     0.000000   0.857143  0.944444
10     10     0.000903   0.900000  1.000000
11     11     0.000903   0.900000  1.000000
12     12     0.008102   1.000000  1.111111
13     13     0.008102   1.000000  1.111111
14     14     0.008102   1.000000  1.111111
15     15     0.000545   0.750000  0.777778
16     16     0.008102   1.000000  1.111111
17     17     0.008102   1.000000  1.111111
18     18     0.005298   0.900000  1.000000

Centrality measures for 2021

In [79]:
bb9 = nx.betweenness_centrality(G9)
cc9 = nx.closeness_centrality(G9)
dc9 = nx.degree_centrality(G9)
centrality = {j:{'betweenness':bb9[j],'closeness': cc9[j],'degree': dc9[j]} for i,j in enumerate(G9.nodes)}
nx.set_node_attributes(G9, centrality)
summary9= pd.DataFrame({'betweenness':bb9, 'closeness':cc9, 'degree':dc9}).reset_index()

In [81]:
concat= [result1, result2,summary9]
finaltable= pd.concat(concat)
finaltable

    index  betweenness  closeness    degree
0       0     0.001170   0.950000  1.052632
1       1     0.005476   1.000000  1.105263
2       2     0.005476   1.000000  1.105263
3       3     0.001170   0.950000  1.052632
4       4     0.001170   0.950000  1.052632
..    ...          ...        ...       ...
15     15     0.006961   1.000000  1.105263
16     16     0.000390   0.703704  0.684211
17     17     0.002430   0.950000  1.052632
18     18     0.006961   1.000000  1.105263
19     19     0.004521   0.904762  1.000000

[178 rows x 4 columns]

In [87]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(finaltable)

    index  betweenness  closeness    degree
0       0     0.001170   0.950000  1.052632
1       1     0.005476   1.000000  1.105263
2       2     0.005476   1.000000  1.105263
3       3     0.001170   0.950000  1.052632
4       4     0.001170   0.950000  1.052632
5       5     0.005476   1.000000  1.105263
6       6     0.000000   0.703704  0.684211
7       7     0.005476   1.000000  1.105263
8       8     0.001170   0.950000  1.052632
9       9     0.000000   0.904762  1.000000
10     10     0.000000   0.904762  1.000000
11     11     0.001170   0.950000  1.052632
12     12     0.005476   1.000000  1.105263
13     13     0.003721   0.950000  1.052632
14     14     0.005476   1.000000  1.105263
15     15     0.005476   1.000000  1.105263
16     16     0.000000   0.826087  0.894737
17     17     0.005476   1.000000  1.105263
18     18     0.005476   1.000000  1.105263
19     19     0.005476   1.000000  1.105263
0       0     0.002631   0.950000  1.052632
1       1     0.008040   1.000000  1.105263
2       2     0.008040   1.000000  1.105263
3       3     0.002631   0.950000  1.052632
4       4     0.002631   0.950000  1.052632
5       5     0.002631   0.950000  1.052632
6       6     0.000344   0.678571  0.631579
7       7     0.004678   0.904762  1.000000
8       8     0.002631   0.950000  1.052632
9       9     0.000344   0.904762  1.000000
10     10     0.000344   0.904762  1.000000
11     11     0.000344   0.904762  1.000000
12     12     0.008040   1.000000  1.105263
13     13     0.005022   0.950000  1.052632
14     14     0.008040   1.000000  1.105263
15     15     0.008040   1.000000  1.105263
16     16     0.000000   0.760000  0.789474
17     17     0.008040   1.000000  1.105263
18     18     0.008040   1.000000  1.105263
19     19     0.007209   0.950000  1.052632
0       0     0.001643   0.950000  1.052632
1       1     0.005187   1.000000  1.105263
2       2     0.005187   1.000000  1.105263
3       3     0.001643   0.950000  1.052632
4       4     0.005187   1.000000  1.105263
5       5     0.001643   0.950000  1.052632
6       6     0.000390   0.730769  0.736842
7       7     0.005187   1.000000  1.105263
8       8     0.001643   0.950000  1.052632
9       9     0.000000   0.904762  1.000000
10     10     0.000000   0.904762  1.000000
11     11     0.000000   0.904762  1.000000
12     12     0.005187   1.000000  1.105263
13     13     0.003544   0.950000  1.052632
14     14     0.005187   1.000000  1.105263
15     15     0.005187   1.000000  1.105263
16     16     0.001949   0.826087  0.894737
17     17     0.005187   1.000000  1.105263
18     18     0.005187   1.000000  1.105263
19     19     0.005187   1.000000  1.105263
0       0     0.004021   0.950000  1.052632
1       1     0.007654   1.000000  1.105263
2       2     0.007654   1.000000  1.105263
3       3     0.000344   0.904762  1.000000
4       4     0.007654   1.000000  1.105263
5       5     0.004021   0.950000  1.052632
6       6     0.001363   0.730769  0.736842
7       7     0.003633   0.904762  1.000000
8       8     0.000344   0.904762  1.000000
9       9     0.000344   0.904762  1.000000
10     10     0.000344   0.904762  1.000000
11     11     0.000344   0.904762  1.000000
12     12     0.007654   1.000000  1.105263
13     13     0.003977   0.950000  1.052632
14     14     0.007654   1.000000  1.105263
15     15     0.007654   1.000000  1.105263
16     16     0.000975   0.730769  0.736842
17     17     0.007654   1.000000  1.105263
18     18     0.007654   1.000000  1.105263
19     19     0.006778   0.950000  1.052632
0       0     0.004021   0.950000  1.052632
1       1     0.006908   1.000000  1.105263
2       2     0.006908   1.000000  1.105263
3       3     0.000344   0.904762  1.000000
4       4     0.006908   1.000000  1.105263
5       5     0.006908   1.000000  1.105263
6       6     0.001363   0.760000  0.789474
7       7     0.002886   0.904762  1.000000
8       8     0.000344   0.904762  1.000000
9       9     0.000344   0.904762  1.000000
10     10     0.000344   0.904762  1.000000
11     11     0.000344   0.904762  1.000000
12     12     0.006908   1.000000  1.105263
13     13     0.003230   0.950000  1.052632
14     14     0.006908   1.000000  1.105263
15     15     0.006908   1.000000  1.105263
16     16     0.000450   0.730769  0.736842
17     17     0.006908   1.000000  1.105263
18     18     0.006908   1.000000  1.105263
19     19     0.006032   0.950000  1.052632
0       0     0.004924   0.947368  1.055556
1       1     0.008440   1.000000  1.111111
2       2     0.008440   1.000000  1.111111
3       3     0.000408   0.900000  1.000000
4       4     0.008440   1.000000  1.111111
5       5     0.008440   1.000000  1.111111
6       6     0.001656   0.750000  0.777778
7       7     0.003516   0.900000  1.000000
8       8     0.000408   0.900000  1.000000
9       9     0.000408   0.900000  1.000000
10     10     0.000408   0.900000  1.000000
11     11     0.000408   0.900000  1.000000
12     12     0.008440   1.000000  1.111111
13     13     0.008440   1.000000  1.111111
14     14     0.008440   1.000000  1.111111
15     15     0.000545   0.720000  0.722222
16     16     0.003924   0.947368  1.055556
17     17     0.008440   1.000000  1.111111
18     18     0.007378   0.947368  1.055556
0       0     0.004519   0.950000  1.052632
1       1     0.007405   1.000000  1.105263
2       2     0.007405   1.000000  1.105263
3       3     0.000000   0.904762  1.000000
4       4     0.007405   1.000000  1.105263
5       5     0.007405   1.000000  1.105263
6       6     0.001595   0.760000  0.789474
7       7     0.002886   0.950000  1.052632
8       8     0.000000   0.904762  1.000000
9       9     0.000000   0.904762  1.000000
10     10     0.000000   0.904762  1.000000
11     11     0.000000   0.904762  1.000000
12     12     0.007405   1.000000  1.105263
13     13     0.002886   0.950000  1.052632
14     14     0.007405   1.000000  1.105263
15     15     0.007405   1.000000  1.105263
16     16     0.000450   0.703704  0.684211
17     17     0.002886   0.950000  1.052632
18     18     0.007405   1.000000  1.105263
19     19     0.007405   1.000000  1.105263
0       0     0.004527   0.947368  1.055556
1       1     0.008102   1.000000  1.111111
2       2     0.008102   1.000000  1.111111
3       3     0.000903   0.900000  1.000000
4       4     0.008102   1.000000  1.111111
5       5     0.008102   1.000000  1.111111
6       6     0.001030   0.750000  0.777778
7       7     0.003575   0.900000  1.000000
8       8     0.000903   0.900000  1.000000
9       9     0.000000   0.857143  0.944444
10     10     0.000903   0.900000  1.000000
11     11     0.000903   0.900000  1.000000
12     12     0.008102   1.000000  1.111111
13     13     0.008102   1.000000  1.111111
14     14     0.008102   1.000000  1.111111
15     15     0.000545   0.750000  0.777778
16     16     0.008102   1.000000  1.111111
17     17     0.008102   1.000000  1.111111
18     18     0.005298   0.900000  1.000000
0       0     0.005286   0.950000  1.052632
1       1     0.006961   1.000000  1.105263
2       2     0.006961   1.000000  1.105263
3       3     0.000755   0.904762  1.000000
4       4     0.006961   1.000000  1.105263
5       5     0.006961   1.000000  1.105263
6       6     0.003077   0.826087  0.894737
7       7     0.001675   0.904762  1.000000
8       8     0.002430   0.950000  1.052632
9       9     0.000000   0.863636  0.947368
10     10     0.000755   0.904762  1.000000
11     11     0.002430   0.950000  1.052632
12     12     0.006961   1.000000  1.105263
13     13     0.002430   0.950000  1.052632
14     14     0.006961   1.000000  1.105263
15     15     0.006961   1.000000  1.105263
16     16     0.000390   0.703704  0.684211
17     17     0.002430   0.950000  1.052632
18     18     0.006961   1.000000  1.105263
19     19     0.004521   0.904762  1.000000